export interface ActivityBudgetLine {
  id: string;
  cost_category: string;
  amount: string;
  original_budget?: string;
}

export interface CreateActivityBudgetLineRequest {
  cost_category: string;
  amount: string;
}

export interface UpdateActivityBudgetLineRequest {
  cost_category?: string;
  amount?: string;
  original_budget?: string;
}

export interface WBSCreateItem {
  element_type: "PHASE" | "SUB_PHASE" | "ACTIVITY";
  name?: string;                          // omitted for PHASE (auto-generated by backend)
  children?: WBSCreateItem[];             // PHASE contains SUB_PHASE | ACTIVITY; SUB_PHASE contains ACTIVITY
  budget_lines?: CreateActivityBudgetLineRequest[]; // only on ACTIVITY nodes
}

export interface CreateProjectCostingProjectRequest {
  name: string;
  client_name: string;
  project_type: string;
  start_date: string;
  expected_end_date: string;
  description: string;
  wbs?: WBSCreateItem[];
}

export interface CreateProjectCostingProjectResponse {
  id: number;
  project_code: string;
  name: string;
  client_name: string;
  project_type: string;
  start_date: string;
  expected_end_date: string;
  description: string;
}

export interface ProjectCostingProject {
  id: number;
  project_code: string;
  name: string;
  status: "DRAFT" | "ACTIVE" | "PENDING" | "REJECTED" | string;
  client_name: string;
  project_type: string;
  description: string;
  start_date: string;
  expected_end_date: string;
  total_budget: string;
  wbs: string;
  financials: string;
  pending_requests_count?: number;
  pending_requests_value?: number;
}

export interface UpdateProjectCostingProjectRequest {
  project_code?: string;
  name?: string;
  status?: string;
  client_name?: string;
  project_type?: string;
  description?: string;
  start_date?: string;
  expected_end_date?: string;
}

export interface ProjectCostingFilterParams {
  ordering?: string;
  search?: string;
}

export interface WBSElement {
  id: string;
  name: string;
}

export interface CreateWBSElementRequest {
  name: string;
}

export interface ProjectActionRequest {
  project_code?: string;
  name?: string;
  status?: string;
  client_name?: string;
  project_type?: string;
  description?: string;
  start_date?: string;
  expected_end_date?: string;
}

export interface ProjectSettings {
  [key: string]: any;
}

